# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_manager_email', models.CharField(max_length=50)),
                ('repo_link', models.CharField(max_length=150)),
                ('documentation_link', models.CharField(max_length=150)),
                ('defect_tracker_link', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=10000)),
                ('data_type', models.CharField(max_length=10000)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.App')),
            ],
        ),
    ]
